# 1. Import libraries

In [1]:
!pip install apyori

Requirement already satisfied: apyori in /opt/anaconda3/lib/python3.9/site-packages (1.1.2)

In [2]:
from apyori import apriori
import pandas as pd

In [3]:
raw_data = pd.read_csv('example2.csv')
df = raw_data.copy()
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

# 2. Filter out the rows with negative values

In [5]:
len(df)

541909

In [6]:
df = df[df['Quantity'] > 0]

In [7]:
len(df)

531285

# 3. Convert table to pivot table with index column = 'Invoice & Items(Columns) = Desc and number of table

In [8]:
df_pivot = pd.pivot_table(data = df,
                               index = 'InvoiceNo',
                               columns = 'Description',
                               values = 'Quantity',
                               aggfunc = 'sum',
                               fill_value = 0)
df_pivot

Description,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,I LOVE LONDON MINI RUCKSACK,NINE DRAWER OFFICE TIDY,OVAL WALL MIRROR DIAMANTE,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,...,returned,taig adjust,test,to push order througha s stock was,website fixed,wrongly coded 20713,wrongly coded 23343,wrongly marked,wrongly marked 23343,wrongly sold (22719) barcode
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536365,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536366,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536367,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536368,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536369,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581586,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581587,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A563185,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A563186,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A563187,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
df_pivot.max(numeric_only = 'true')

Description
 4 PURPLE FLOCK DINNER CANDLES      12
 50'S CHRISTMAS GIFT BAG LARGE     400
 DOLLY GIRL BEAKER                 400
 I LOVE LONDON MINI BACKPACK        50
 I LOVE LONDON MINI RUCKSACK         1
                                  ...
wrongly coded 20713                800
wrongly coded 23343               1000
wrongly marked                      48
wrongly marked 23343               200
wrongly sold (22719) barcode       170
Length: 4077, dtype: int64

In [10]:
df_pivot.drop(columns = ['POSTAGE'],inplace=True)
df_pivot.drop(columns = ['wrongly coded 20713'],inplace=True)
df_pivot.drop(columns = ['wrongly coded 23343'],inplace=True)
df_pivot.drop(columns = ['wrongly marked 23343'],inplace=True)
df_pivot.drop(columns = ['wrongly marked'],inplace=True)
df_pivot.drop(columns = ['wrongly sold (22719) barcode'],inplace=True)

df_pivot

Description,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,I LOVE LONDON MINI RUCKSACK,NINE DRAWER OFFICE TIDY,OVAL WALL MIRROR DIAMANTE,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,...,mailout,mailout,michel oops,on cargo order,rcvd be air temp fix for dotcom sit,returned,taig adjust,test,to push order througha s stock was,website fixed
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536365,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536366,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536367,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536368,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536369,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581586,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581587,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A563185,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A563186,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A563187,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
def dataframe_to_list_of_lists(df):
    transactions = []
    for index, row in df.iterrows():
        items = [column for column in df.columns if row[column] > 0]
        transactions.append(items)
    return transactions

In [12]:
transactions = dataframe_to_list_of_lists(df_pivot)

In [13]:
for i in range(10):
    print(str(i) + "-" + str(transactions[i]))

0-['CREAM CUPID HEARTS COAT HANGER', 'GLASS STAR FROSTED T-LIGHT HOLDER', 'KNITTED UNION FLAG HOT WATER BOTTLE', 'RED WOOLLY HOTTIE WHITE HEART.', 'SET 7 BABUSHKA NESTING BOXES', 'WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN']
1-['HAND WARMER RED POLKA DOT', 'HAND WARMER UNION JACK']
2-['ASSORTED COLOUR BIRD ORNAMENT', 'BOX OF 6 ASSORTED COLOUR TEASPOONS', 'BOX OF VINTAGE ALPHABET BLOCKS', 'BOX OF VINTAGE JIGSAW BLOCKS ', 'DOORMAT NEW ENGLAND', 'FELTCRAFT PRINCESS CHARLOTTE DOLL', 'HOME BUILDING BLOCK WORD', 'IVORY KNITTED MUG COSY ', 'LOVE BUILDING BLOCK WORD', "POPPY'S PLAYHOUSE BEDROOM ", "POPPY'S PLAYHOUSE KITCHEN", 'RECIPE BOX WITH METAL HEART']
3-['BLUE COAT RACK PARIS FASHION', 'JAM MAKING SET WITH JARS', 'RED COAT RACK PARIS FASHION', 'YELLOW COAT RACK PARIS FASHION']
4-['BATH BUILDING BLOCK WORD']
5-[' SET 2 TEA TOWELS I LOVE LONDON ', 'ALARM CLOCK BAKELIKE GREEN', 'ALARM CLOCK BAKELIKE PINK', 'ALARM CLOCK BAKELIKE RED ', 'CHARLOTTE BAG DOLLY GIRL DESIGN', 'CIRCUS PARADE LUNCH BOX ', 'INFLATABLE POLITICAL GLOBE ', 'LUNCH BOX I LOVE LONDON', 'MINI JIGSAW CIRCUS PARADE ', 'MINI JIGSAW SPACEBOY', 'MINI PAINT SET VINTAGE ', 'PANDA AND BUNNIES STICKER SHEET', 'RED TOADSTOOL LED NIGHT LIGHT', 'ROUND SNACK BOXES SET OF4 WOODLAND ', 'SET/2 RED RETROSPOT TEA TOWELS ', 'SPACEBOY LUNCH BOX ', 'STARS GIFT TAPE ', 'VINTAGE HEADS AND TAILS CARD GAME ', 'VINTAGE SEASIDE JIGSAW PUZZLES']
6-["PAPER CHAIN KIT 50'S CHRISTMAS "]
7-['HAND WARMER RED POLKA DOT', 'HAND WARMER UNION JACK']
8-['CREAM CUPID HEARTS COAT HANGER', 'EDWARDIAN PARASOL RED', 'GLASS STAR FROSTED T-LIGHT HOLDER', 'KNITTED UNION FLAG HOT WATER BOTTLE', 'RED WOOLLY HOTTIE WHITE HEART.', 'RETRO COFFEE MUGS ASSORTED', 'SAVE THE PLANET MUG', 'SET 7 BABUSHKA NESTING BOXES', 'VINTAGE BILLBOARD DRINK ME MUG', 'VINTAGE BILLBOARD LOVE/HATE MUG', 'WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN', 'WOOD 2 DRAWER CABINET WHITE FINISH', 'WOOD S/3 CABINET ANT WHITE FINISH', 'WOODEN FRAME ANTIQUE WHITE ', 'WOODEN PICTURE FRAME WHITE FINISH']
9-['VICTORIAN SEWING BOX LARGE']

# 4. import apyori and run apriori algorithm

In [14]:
rules = apriori(transactions, 
                min_support = 0.01, 
                min_confidence = 0.5, 
                min_lift = 3, 
                min_length = 2, 
                max_length = 3)

In [15]:
results = list(rules)

In [16]:
type(results)

list

In [17]:
results_df = pd.DataFrame(results)
results_df.head()

,items,support,ordered_statistics
0,"(PACK OF 72 RETROSPOT CAKE CASES, 60 CAKE CASE...",0.012018,"[((60 CAKE CASES DOLLY GIRL DESIGN), (PACK OF ..."
1,"(PACK OF 72 RETROSPOT CAKE CASES, 60 TEATIME F...",0.022497,"[((60 TEATIME FAIRY CAKE CASES), (PACK OF 72 R..."
2,"(ALARM CLOCK BAKELIKE CHOCOLATE, ALARM CLOCK B...",0.013756,"[((ALARM CLOCK BAKELIKE CHOCOLATE), (ALARM CLO..."
3,"(ALARM CLOCK BAKELIKE PINK, ALARM CLOCK BAKELI...",0.010926,"[((ALARM CLOCK BAKELIKE CHOCOLATE), (ALARM CLO..."
4,"(ALARM CLOCK BAKELIKE RED , ALARM CLOCK BAKELI...",0.014501,"[((ALARM CLOCK BAKELIKE CHOCOLATE), (ALARM CLO..."

In [18]:
def convert_dataFrame(results):
    lhs = [', '.join(result[2][0][0]) for result in results]  # Join multiple LHS items by comma
    rhs = [', '.join(result[2][0][1]) for result in results]  # Join multiple RHS items by comma
    supports = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts = [result[2][0][3] for result in results]
    return list(zip(lhs, rhs, supports, confidences, lifts))

In [19]:
resultFrame = pd.DataFrame(convert_dataFrame(results),columns = ["Left Hand Side","Right Hand Side","Support","Confidence","Lift"])
resultFrame

,Left Hand Side,Right Hand Side,Support,Confidence,Lift
0,60 CAKE CASES DOLLY GIRL DESIGN,PACK OF 72 RETROSPOT CAKE CASES,0.012018,0.553776,8.447597
1,60 TEATIME FAIRY CAKE CASES,PACK OF 72 RETROSPOT CAKE CASES,0.022497,0.547101,8.345784
2,ALARM CLOCK BAKELIKE CHOCOLATE,ALARM CLOCK BAKELIKE GREEN,0.013756,0.647196,13.297902
3,ALARM CLOCK BAKELIKE CHOCOLATE,ALARM CLOCK BAKELIKE PINK,0.010926,0.514019,13.218749
4,ALARM CLOCK BAKELIKE CHOCOLATE,ALARM CLOCK BAKELIKE RED,0.014501,0.682243,13.071023
...,...,...,...,...,...
401,REGENCY TEA PLATE GREEN,"REGENCY TEA PLATE PINK, REGENCY TEA PLATE ROSES",0.012664,0.669291,50.099816
402,REGENCY TEA PLATE GREEN,"REGENCY TEA PLATE ROSES , ROSES REGENCY TEACUP...",0.010280,0.543307,39.781933
403,SET/6 RED SPOTTY PAPER CUPS,"SET/6 RED SPOTTY PAPER PLATES, SET/20 RED RETR...",0.013161,0.619159,33.695630
404,"WHITE HANGING HEART T-LIGHT HOLDER, WOODEN FRA...",WOODEN PICTURE FRAME WHITE FINISH,0.010826,0.643068,11.771649
405,WOODEN TREE CHRISTMAS SCANDINAVIAN,"WOODEN STAR CHRISTMAS SCANDINAVIAN, WOODEN HEA...",0.011472,0.683432,35.468005